version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stonecraft-web
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${SUPABASE_CONNECTION_STRING}
    env_file:
      - .env
    volumes:
      - ./backend/StoneCraft.Api/appsettings.Development.json:/app/appsettings.Development.json:ro
